# Checks to find any diffs in schema
name: Schema Check

on:
  workflow_dispatch:
  pull_request:

env:
  LATEST_SCHEMA_PATH: /home/runner/work/dbt/dbt/new_schemas

jobs:
  check:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: |
                ${{ secrets.SCHEMA_SSH_PRIVATE_KEY }}
                
      - name: Clone schemas.getdbt.com
        run: |
          git clone https://github.com/dbt-labs/schemas.getdbt.com.git 
          git clone https://github.com/dbt-labs/dbt.git 
          ls
          pwd
      
      - name: Run schema script
        run: |
          pwd
          ls
          cd dbt
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r dev-requirements.txt -r editable-requirements.txt
          ls scripts
          python scripts/collect-artifact-schema.py --path ${LATEST_SCHEMA_PATH}
          cd /home/runner/work/dbt/dbt
          ls
          echo =========
          ls schemas.getdbt.com
          echo =========
          ls schemas.getdbt.com/dbt 
          echo =========
          cp -r new_schemas/dbt schemas.getdbt.com
          ls schemas.getdbt.com/dbt 
          echo =========
          cd schemas.getdbt.com
          ls
          echo =========
          git diff -I='*[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T' \
          -I='*[0-9]{1}.[0-9]{2}.[0-9]{1}(rc[0-9]|b[0-9]| )'
