# Checks to find any diffs in schema
name: Schema Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout dbt repo
        uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: |
                ${{ secrets.SCHEMA_SSH_PRIVATE_KEY }}
                
      - name: Checkout schema repo
        uses: actions/checkout@v2
        with:
          repository: dbt-labs/schemas.getdbt.com
          ref: 'main'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
