# Checks to find any diffs in schema
name: Schema Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: |
                ${{ secrets.SCHEMA_SSH_PRIVATE_KEY }}
                
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          git clone https://github.com/dbt-labs/dbt
          git clone https://github.com/dbt-labs/schemas.getdbt.com.git          
          ls
          cd dbt
          pip install -r dev-requirements.txt
          
      - name: Run schema script
        run: |
          python scripts/collect-artifact-schema.py .
          ls
          

